drop table if exists folders;
drop table if exists notes;

create table folders (
    id integer primary key generated by default as identity,
    name text not null,
    modified timestamptz default now() not null
);

create table notes (
    id integer primary key generated by default as identity,
    name text not null,
    content text not null,
    modified timestamptz default now() not null,
    "folderId" INTEGER REFERENCES folders(id) ON DELETE CASCADE NOT NULL
);